version: '3.7'
services:

  fronted:
    image: jupyter/scipy-notebook:2023-02-28
    ports:
      - "10000:8888"
    networks:
      - front-tier
      - back-tier
    
  backend:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier: {}
  back-tier: {}